theme: jekyll-theme-midnight

# http://deanattali.com/beautiful-jekyll/

# url is the full website URL
# baseurl is the website's URL without the hostname
url: "http://OgoxHammerschild.github.io"
baseurl: ""

title: OgoxHammerschild.github.io
description: A small collection of some of my repositories and code snippets!

avatar: https://avatars3.githubusercontent.com/u/15057773?s=460&v=4
